spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://localhost:3306/hhplus?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/hhplus
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 60000
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.orm.deprecation: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework: DEBUG

---
spring.config.activate.on-profile: local, test

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**

